### ISSUE TITLE
Не используй верстку в  js

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#15]
![Снимок экрана от 2019-09-16 13-45-31](https://user-images.githubusercontent.com/31854808/64938514-5f727800-d888-11e9-90eb-71ffdbb3bcb0.png)

**Comment by madnessJs** [comment]
ммм, вставлять сразу на страницу и скрывать display: none?

**Comment by GoodDayTodayOkey** [comment]
Да, но лучше через модификакторы разруливаться, а не стили инлайново менять)
