### ISSUE TITLE
Оформить код с использованием es6 классов 

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#17]
![Снимок экрана от 2019-09-16 13-57-35](https://user-images.githubusercontent.com/31854808/64939013-fc81e080-d889-11e9-80a8-50b22241cfde.png)
![Снимок экрана от 2019-09-16 13-58-03](https://user-images.githubusercontent.com/31854808/64939022-04418500-d88a-11e9-9a88-a59ae0f0da3d.png)

**Comment by madnessJs** [comment]
Так и до тестов с mvc доберемся)

**Comment by GoodDayTodayOkey** [comment]
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md пункт 6

**Comment by madnessJs** [comment]
Перенес не весь код, оставил инициализацию плагинов в js файле страницы и уникальные вещи(по типу кнопки фильтра на странице номеров)

**Comment by GoodDayTodayOkey** [comment]
Нужно подправить следующие вещи:
![Снимок экрана от 2019-10-03 19-44-56](https://user-images.githubusercontent.com/31854808/66128951-19077200-e619-11e9-8d17-bc2372fc8337.png) 
![Снимок экрана от 2019-10-03 19-45-18](https://user-images.githubusercontent.com/31854808/66129002-3b998b00-e619-11e9-87dd-2df9aa47bdf1.png)не обращайся к свойству объекта, используй сразу его свойство
Вот это все и ниже нужно переписать: 1) если нужно свернуть массив до значений используй  метод reduce, далее три свича можно свернуть до перебора по массиву [{1: ['спальня','кровать','ванная комната'], {2: ...}, {5: ...}}]. Для слайдера календаря и т.д. на страницах в js тоже используй классы.

**Comment by GoodDayTodayOkey** [comment]
тут сразу отпишусь по стилям, чтобы не писать отдельно ишью подправь width два значения в  rem
![Снимок экрана от 2019-10-03 20-16-08](https://user-images.githubusercontent.com/31854808/66129838-d8a8f380-e61a-11e9-9a81-4ae26224064c.png)

**Comment by madnessJs** [comment]
1) Те не -
const amount = item.querySelector('.dropdown__amount');
amount.textContent = +amount.textContent - 1;
А - item.querySelector('.dropdown__amount').textContent = +amount.textContent - 1;
2) Я понимаю, что делает reduce, но в данном случае нужно не к одному значению свести, а к 3. Тк в поле будет вставлено не "10 предметов мебели", к примеру, а "3 того, 5 того и 2 того"

**Comment by madnessJs** [comment]
Поменял код этого метода в классе DropdownComfort, избавился от 3-х switch'ей и let переменных. Но сделал все равно не как ты наверное имел ввиду)

**Comment by GoodDayTodayOkey** [comment]
Примерно так, в дальнейшем давай сам)
![Снимок экрана от 2019-10-04 22-44-28](https://user-images.githubusercontent.com/31854808/66221169-a5d52d00-e6f8-11e9-95b3-47877c49ab2a.png)
тут не поправил
![Снимок экрана от 2019-10-04 22-47-00](https://user-images.githubusercontent.com/31854808/66221453-31e75480-e6f9-11e9-8f5c-50f8640f2558.png)

Я вот о чем писал, дальше сам пройдись везде
![Снимок экрана от 2019-10-04 22-48-14](https://user-images.githubusercontent.com/31854808/66221440-2a27b000-e6f9-11e9-9a40-c85a6185a652.png)

**Comment by madnessJs** [comment]
Разбирался в твоем решении для метода apply. Понять как работает понял, но самому до такого решения пока наверное не додуматься. Попытался перенести твое решение на метод другого класса - не получилось) Но решил другим способом, понятным мне. Тоже применил метод reduce

**Comment by GoodDayTodayOkey** [comment]
К сожалению так не подойдет, пример с младенцами один в один  похож, на приведенный мною пример. За время  стажерского задания ты  должен научится владеть редьюсом, мапом и т.д. Потому что данные которые прилетеют с сервера зачастую сохранены не так как требуется на фронте, и конвертировать к требуемому формату не должно вызывать проблем.

**Comment by madnessJs** [comment]
> К сожалению так не подойдет, пример с младенцами один в один похож, на приведенный мною пример. За время стажерского задания ты должен научится владеть редьюсом, мапом и т.д. Потому что данные которые прилетеют с сервера зачастую сохранены не так как требуется на фронте, и конвертирование их к требуемому формату не должно вызывать проблем.

В каком месте он похож? Я решил таким образом, насколько понимаю сам.
Нужно решить каким-то определенным образом?

**Comment by GoodDayTodayOkey** [comment]
В том что тебе опять нужно получить строку на основе массива данных. Давай ты сделаешь так, вычислишь общее количество гостей с помощью редьюса и положишь их в константу, в другую константу поместишь количество младенцев, а в this.input.value положишь сразу строку с помощью этих констант и редьюсера который пробежится по массиву объектов [ {guest: 'гостей', baby: 'младенцев',}, {guest:'гость', baby: 'младенец'} ...] Второе замечание в использованием сразу свойства так и не подправил(

**Comment by madnessJs** [comment]
По второму замечанию я предложил решение. Ты сказал отпишешься, но забыл)
![image](https://user-images.githubusercontent.com/46949445/66397019-a49b4d00-e9e3-11e9-9bc1-8214881f4d54.png)

**Comment by GoodDayTodayOkey** [comment]
Пробегись еще в pages по каждому из объектов forEach, чтобы для каждого элемента создавался инстанс - так как ты тут сделал для likeButtons
![Screenshot 2019-10-09 at 10 12 18](https://user-images.githubusercontent.com/31854808/66449952-f8a83f00-ea80-11e9-8988-fd7f936ebd20.png)

**Comment by GoodDayTodayOkey** [comment]
Переписать с использованием every 
![Снимок экрана от 2019-10-08 20-27-12](https://user-images.githubusercontent.com/31854808/66449991-23929300-ea81-11e9-8bda-19084d486279.png)

**Comment by madnessJs** [comment]
Все сделал, осталось только reduce.
Понимать как работает метод понимаю, задачки сегодня порешал с reduce, map. Вот убей, но не могу понять как применить reduce в методе

**Comment by madnessJs** [comment]
Только с использованием 2 редьюсеров. С одним тут никак не придумаю
![image](https://user-images.githubusercontent.com/46949445/66545834-40dc6580-eb44-11e9-953d-48a56c577f36.png)

**Comment by madnessJs** [comment]
Решил!
![image](https://user-images.githubusercontent.com/46949445/66551793-d41b9800-eb50-11e9-94c0-2ebdc62ea424.png)
