### ISSUE TITLE
Используй тернарник

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#19]
![Снимок экрана от 2019-09-16 14-26-41](https://user-images.githubusercontent.com/31854808/64940379-0574b100-d88e-11e9-9e0a-f00724e82620.png)

**Comment by madnessJs** [comment]
Не приложу ума даже, как его тут использовать...

**Comment by GoodDayTodayOkey** [comment]
К примеру можно был так
![Снимок экрана от 2019-09-19 21-36-48](https://user-images.githubusercontent.com/31854808/65253907-a0d38380-db25-11e9-9f7a-2d5bc3072102.png)
но будет лучше если от будет не стилями управлять, а возвращать модификатор для класса к примеру (...? 'showed' : '');
