### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#2]
Разделить зависимости необходимые для dev и prod сборки

**Comment by madnessJs** [comment]
Насколько я понял нужно так разделить?
![image](https://user-images.githubusercontent.com/46949445/64000244-f9f35d00-cb0d-11e9-8580-409d21ac2341.png)

**Comment by GoodDayTodayOkey** [comment]
Нет,  в девдепеденсив у тебя должно остаться только что не используется для полноценной сборки проекта, т.е. необдимое тольлко для дев режима. к примеру EsLint(который нужно добавить в проект)

**Comment by GoodDayTodayOkey** [comment]
Вот этих два пакета тоже нужно перенести, ты их используешь для прод сборки
![Снимок экрана от 2019-09-10 18-07-28](https://user-images.githubusercontent.com/31854808/64608932-f60ce800-d3f5-11e9-997e-1640b7b9977b.png)
