### ISSUE TITLE
Используй модификаторы не нужно принять инлайново стили

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#20]
![Снимок экрана от 2019-09-16 14-31-11](https://user-images.githubusercontent.com/31854808/64940638-a95e5c80-d88e-11e9-80e1-cb3e8082b643.png)

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-20 20-43-14](https://user-images.githubusercontent.com/31854808/65331643-63372f00-dbe7-11e9-8b56-67b6a1a8fe32.png)
![Снимок экрана от 2019-09-20 20-43-25](https://user-images.githubusercontent.com/31854808/65331644-63372f00-dbe7-11e9-941c-47358e18ce6b.png)
![Снимок экрана от 2019-09-20 20-43-43](https://user-images.githubusercontent.com/31854808/65331645-63372f00-dbe7-11e9-8160-69ab04b32d96.png)

**Comment by madnessJs** [comment]
Где ты это нашел?) я поправил это уже

**Comment by GoodDayTodayOkey** [comment]
![Peek 2019-09-24 18-20](https://user-images.githubusercontent.com/31854808/65507425-1c537d00-def8-11e9-84f3-f205cd78815d.gif)
 все еще остались места, а для чего нужен это класс?
![Снимок экрана от 2019-09-24 18-22-32](https://user-images.githubusercontent.com/31854808/65507503-49a02b00-def8-11e9-926e-81ba09b039ec.png)

**Comment by madnessJs** [comment]
display: none добавляет функция jquery slideToggle(). Тут требования противоречат сами себе) С одной стороны нужно использовать jquery, а с другой - не менять инлайново стили)
.scroll-none нужен для скрытия прокрутки у документа.
![image](https://user-images.githubusercontent.com/46949445/65520640-941da980-def0-11e9-9bf7-b63fb1a00c03.png)

**Comment by GoodDayTodayOkey** [comment]
Почему противоречат? Добавляй с помощью JQuery  модификатор классу а в нем уже прописывай свойство display: none

**Comment by GoodDayTodayOkey** [comment]
А для чего ее скрывать это есть в макетах?

**Comment by madnessJs** [comment]
> А для чего скрывать полосу прокрутки это есть в макетах?

Нет. Это сделано, чтобы на мобильной версии, на странице выбора номеров, она скрывалась когда показывается фильтр

**Comment by madnessJs** [comment]
> Почему противоречат? Добавляй с помощью JQuery модификатор классу а в нем уже прописывай свойство display: none

Окей, переделаю когда буду js код на классы переносить

**Comment by GoodDayTodayOkey** [comment]
А почему ее нужно скрывать?

**Comment by madnessJs** [comment]
> А почему ее нужно скрывать?

потому что появятся две полосы. Ты попробуй сам

**Comment by madnessJs** [comment]
у боди класс scroll-none
![image](https://user-images.githubusercontent.com/46949445/65586710-473be080-df8d-11e9-87db-c2e5f412229c.png)

у боди нету этого класса
![image](https://user-images.githubusercontent.com/46949445/65586743-57ec5680-df8d-11e9-98cd-ecb0e361324f.png)
