### ISSUE TITLE
Именование элементов

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#21]
Пробегись по всем проекту плиз, именование элементов должны соответствовать Бэм
![Снимок экрана от 2019-09-16 15-47-04](https://user-images.githubusercontent.com/31854808/64944821-6786e380-d899-11e9-8827-e635db57b6fd.png)

**Comment by madnessJs** [comment]
> Пробегись по всем проекту плиз, именование элементов должны соответствовать Бэм
> ![Снимок экрана от 2019-09-16 15-47-04](https://user-images.githubusercontent.com/31854808/64944821-6786e380-d899-11e9-8827-e635db57b6fd.png)

А что тут не так? Не нашел статьи о правильном именовании по БЭМ в js

**Comment by GoodDayTodayOkey** [comment]
неверное именование модификаторов,не используй id
![Снимок экрана от 2019-09-20 20-52-55](https://user-images.githubusercontent.com/31854808/65333131-1d2f9a80-dbea-11e9-94a1-ac365f000772.png)
![Снимок экрана от 2019-09-20 20-53-20](https://user-images.githubusercontent.com/31854808/65333198-38020f00-dbea-11e9-9ad5-6e4ef5857456.png)
![Снимок экрана от 2019-09-20 20-57-17](https://user-images.githubusercontent.com/31854808/65333798-587e9900-dbeb-11e9-989d-ef34917de70d.png)
![Снимок экрана от 2019-09-20 20-57-58](https://user-images.githubusercontent.com/31854808/65333817-5f0d1080-dbeb-11e9-8126-ffeb867336e6.png)
![Снимок экрана от 2019-09-20 20-58-48](https://user-images.githubusercontent.com/31854808/65333965-aabfba00-dbeb-11e9-80d2-9ab7b3284799.png)
![Снимок экрана от 2019-09-20 21-00-20](https://user-images.githubusercontent.com/31854808/65334360-6c76ca80-dbec-11e9-86d8-28a11389c72f.png)


именование блоков должно характиризовать смысл, а не внешний вид, мы не используем миксы
![Снимок экрана от 2019-09-20 20-56-41](https://user-images.githubusercontent.com/31854808/65333638-12293a00-dbeb-11e9-9b3b-7c8652fa0404.png)
![Снимок экрана от 2019-09-20 20-57-03](https://user-images.githubusercontent.com/31854808/65333669-1e14fc00-dbeb-11e9-83eb-0dd343039767.png)
![Снимок экрана от 2019-09-20 21-00-47](https://user-images.githubusercontent.com/31854808/65334507-b5c71a00-dbec-11e9-9885-fac131413128.png)
![Снимок экрана от 2019-09-20 21-01-07](https://user-images.githubusercontent.com/31854808/65334515-b95aa100-dbec-11e9-9f03-7e4a3ef118e6.png)
![Снимок экрана от 2019-09-20 21-02-48](https://user-images.githubusercontent.com/31854808/65334590-e018d780-dbec-11e9-9373-4d90c8704316.png)


Именование блока должно более точно отображать что оно характеризует, field очень абстрактно.
![Снимок экрана от 2019-09-20 20-59-06](https://user-images.githubusercontent.com/31854808/65334042-d5aa0e00-dbeb-11e9-80f8-081397af5f64.png)
![Снимок экрана от 2019-09-20 20-59-23](https://user-images.githubusercontent.com/31854808/65334220-2883c580-dbec-11e9-96c5-2dca4b11d1da.png)

Именование элементов должно характеризовать сущность 
![Снимок экрана от 2019-09-20 21-00-38](https://user-images.githubusercontent.com/31854808/65334485-a8119480-dbec-11e9-8189-e397eb8c8332.png)
![Снимок экрана от 2019-09-20 21-01-56](https://user-images.githubusercontent.com/31854808/65334551-cecfcb00-dbec-11e9-9577-5bc8ad90d3c4.png)
![Снимок экрана от 2019-09-20 21-02-37](https://user-images.githubusercontent.com/31854808/65334571-d8f1c980-dbec-11e9-8a8f-2ae4063adb1c.png)

**Comment by madnessJs** [comment]
По donut, к нему не прицепить линейный градиент другим способом, кроме как через js. Это настолько критично?

**Comment by madnessJs** [comment]
Мы не используем миксы
----
Это ты про смешивание классов с visually-hidden?

**Comment by madnessJs** [comment]
Если в компоненте используется сложная микросетка все равно нужно каждому блоку давать осмысленное название?
![image](https://user-images.githubusercontent.com/46949445/65424350-f9e83380-de13-11e9-95b4-e2dd4b6b2698.png)
Вот если своими словами что это? Информация о номере. А как логически отделить верхнюю от нижней части?

**Comment by GoodDayTodayOkey** [comment]
Про donut я писал про модификатор, но ты уже подправил) Да, это смешение классов. 
![Снимок экрана от 2019-09-24 17-05-55](https://user-images.githubusercontent.com/31854808/65502750-a64a1880-deed-11e9-8f05-1b6728c861b1.png)
Вот здесь это выглядит не очень, можно де назвать .login_label   либо .login__field
По описанной микро сетке ты нормально разбил на элементы, так и нужно делать)

**Comment by madnessJs** [comment]
> Вот здесь это выглядит не очень, можно де назвать .login_label либо .login__field

ммм...давай сделаю checkbox-rich__field_hidden?

**Comment by GoodDayTodayOkey** [comment]
Это ишью буду закрывать совместно с ишью про именование блоков.
