### ISSUE TITLE
Убрать let из проекта

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#22]
Не используй его где возможно обойтись без него
![Снимок экрана от 2019-09-16 15-49-08](https://user-images.githubusercontent.com/31854808/64944962-c187a900-d899-11e9-9e88-7b23c4cbd030.png)

**Comment by madnessJs** [comment]
Эти переменные изменяются нижерасположенным циклом.
![image](https://user-images.githubusercontent.com/46949445/65150411-c0d34c00-da2c-11e9-8825-07f894ffc5e1.png)

**Comment by GoodDayTodayOkey** [comment]
А для чего тут вообще forEach? можно обойтись map, да и мутировать input который и лексикал инвайромент это жесть, не делай так) Давай обсудим код, когда оформишь это в классе)

**Comment by madnessJs** [comment]
жду проверки #17 issue
