### ISSUE TITLE
Организация хранения данных

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#24]
Здесь явно напрашивается использовать массив данных, если будет желание можно в  json  сохранить
![Снимок экрана от 2019-09-16 16-04-18](https://user-images.githubusercontent.com/31854808/64945902-de24e080-d89b-11e9-85ba-04b91735f15a.png)

**Comment by madnessJs** [comment]
Почему массив? Тут как по мне явно объект напрашивается. Есть ключи и значения (image: тото, text: тото)

**Comment by GoodDayTodayOkey** [comment]
Я не про объекты миксинах, а про повторяющиеся блоки которые можно перебрать в цикле. Для перебора в цикле можно использовать массив объектов (объектами будут те что передаются в миксин).

**Comment by GoodDayTodayOkey** [comment]
Блин, опять коммит объединяет несколько ишьюсов(
