### ISSUE TITLE
Не все цвета вынесены в константу

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#25]
Пробегись по проекту плиз
![Снимок экрана от 2019-09-16 16-07-14](https://user-images.githubusercontent.com/31854808/64946073-3f4cb400-d89c-11e9-89f2-36fa17ae4d41.png)
![Снимок экрана от 2019-09-16 16-07-22](https://user-images.githubusercontent.com/31854808/64946074-3f4cb400-d89c-11e9-9c48-09c6082bd881.png)
![Снимок экрана от 2019-09-16 16-07-31](https://user-images.githubusercontent.com/31854808/64946077-3f4cb400-d89c-11e9-959f-0357c06e0535.png)

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-20 20-23-14](https://user-images.githubusercontent.com/31854808/65330425-bf4c8400-dbe4-11e9-9cbb-f9c1a90c9862.png)
![Снимок экрана от 2019-09-20 20-23-27](https://user-images.githubusercontent.com/31854808/65330426-bfe51a80-dbe4-11e9-8cd1-e2a3fdcf1f40.png)

**Comment by madnessJs** [comment]
В требованиях сказано не лезть в стили плагинов, я и не лез

**Comment by madnessJs** [comment]
Заменил скопированные стили плагинов в стили компонентов на импорт стилей плагина из node_modules

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-24 16-50-18](https://user-images.githubusercontent.com/31854808/65501608-7bf75b80-deeb-11e9-9409-b3d1ac045c24.png)
еще один остался
