### ISSUE TITLE
Перевести px => rem

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#26]
Пробегись по всему проекту плиз
![Снимок экрана от 2019-09-16 16-09-20](https://user-images.githubusercontent.com/31854808/64946172-6d31f880-d89c-11e9-87be-a543b08ba284.png)

**Comment by madnessJs** [comment]
> Пробегись по всему проекту плиз
> ![Снимок экрана от 2019-09-16 16-09-20](https://user-images.githubusercontent.com/31854808/64946172-6d31f880-d89c-11e9-87be-a543b08ba284.png)

Ориентировался на это требование.
![image](https://user-images.githubusercontent.com/46949445/65242713-618a4000-daef-11e9-87d6-1e2dd371c415.png)
Как я понял оно не обязывает использовать rem на всем проекте.
