### ISSUE TITLE
Не используй селекторы по тэгам

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#27]
![Снимок экрана от 2019-09-16 16-30-32](https://user-images.githubusercontent.com/31854808/64947496-5214b800-d89f-11e9-9d6f-782f36ad90fe.png)

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-20 20-28-03](https://user-images.githubusercontent.com/31854808/65330620-2cf8b000-dbe5-11e9-930f-e6d6f4bcd647.png)
![Снимок экрана от 2019-09-20 20-34-02](https://user-images.githubusercontent.com/31854808/65331006-0ab36200-dbe6-11e9-816c-72adff0a1eba.png)
![Снимок экрана от 2019-09-20 20-34-15](https://user-images.githubusercontent.com/31854808/65331007-0b4bf880-dbe6-11e9-82de-b4e400c71250.png)

**Comment by madnessJs** [comment]
тут я думал нельзя глобально использовать стили по тегам...
