### ISSUE TITLE
Удалить в проекте ненужные стили

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#28]
у тебя  span и так инлайновый элемент, для чего еще задавать в стилях?
![Снимок экрана от 2019-09-16 16-44-39](https://user-images.githubusercontent.com/31854808/64948458-4c1fd680-d8a1-11e9-9818-3ca98a495bd0.png)

**Comment by madnessJs** [comment]
Это флекс элемент. Задал как защиту от дурака (если в будущем изменится тип контейнера на блочный, то span.advantage__icon будет 0x0)
