### ISSUE TITLE
Именование блоков

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#29]
Подошло время обсудить именование блоков)
![Снимок экрана от 2019-09-24 18-40-49](https://user-images.githubusercontent.com/31854808/65508679-ee236c80-defa-11e9-8d64-696797c5d793.png)
Смотри, давай приведем проект к единообразию кнопки следует называть btn-like, btn-sign-up, btn-pagination и т.д. Не надо отталкиваться от их внешнего вида.
Также следует обратить внимание на то что ты именуешь блоки исходя из того что они представляют в html коде, а нужно именовать из того что они представляют из себя для пользователя. То есть pagination отличное именование, а вот forms, dropdowns, radio-button, checkbox, text-fieald-default, text-field-subscribtion, toggle-button ничего не говорят, и эти имена приведут к тому что например чекбоксы могут быть в разных местах сайта, и нести разный функционал, а по именованию их придется размещать в одной папке, как получилось с кнопками и формами. Отталкивайся в именовании от того что они представляют из себя для юзера.

**Comment by madnessJs** [comment]
По кнопкам понятно.
forms это папка для группировки форм проекта. В ней лежит форма form-registration. Чем не отличное название для блока. Форма регистрации, даже название говорящее.
Компонент toggle-button например чем плох? Как я понял твой посыл, он используется у нас один раз(пока) для подписки на новости при регистрации. И его нужно назвать например subscribe-newsletter(ну или как то так). Но по мне название toggle-button говорит что это переключатель. И его можно использовать вне любого контекста. Пусть это будет подписка на новости, либо например "Выйти из системы через 15 минут" при входе в аккаунт на сайте.
Если я что-то не так понял, поправь)

**Comment by GoodDayTodayOkey** [comment]
Да, я не совсем точно выразился, если планируешь к ним относится как к переиспользуемым элементам в составе блока имеющего осмысленное именование для пользователя, то их следует именовать исходя из того что они представляют с точки зрения кода. Например radio-button  => radoInput, toggle-button => checkboxInput. И будет нормальным использовать эти блоки внутри других блоков имеющие именования исходя из пользовательского видения. У тебя к примеру сейчас три чекбокса и toggle-button (хотя должен быть один и три блока имеющие различную верстку с отдельное именование) Стилизовать чекбоксы можно с помощью модификаторов. Посмотри еще пожалуйста в стандартах на риззоме про именование блоков, насколько помню используем camelCase именование а не Kebab Case) Про формы, если с просить пользователя. Для кнопок тоже по идеи можно сделать компоненту Button как переиспользуемой, а уже btn-like и т.д. будут добавлять новую верстку в существующий и стилизовать эту компаненту с помощью модификаторов)  https://pugjs.org/language/mixins.html#mixin-blocks Про формы тут можно просто обратиться к окружающим и скорее всего они скажут что это регистрация на сайте. Поэтому блок можно именовать как signUp, roomSelection, hotelSearch, signUp

**Comment by madnessJs** [comment]
Я для именования блоков использую-такую-нотацию, а не кебаб кейс)
По кнопкам - т.е. я делаю один блок button(и link для ссылок) и ему в параметр передаю тему кнопки? Например +button(theme: with-border-gradient), а в миксине уже отдаю верстку в соответствии от выбранной темы.
По формам - все равно не понял... у меня блок form-registration, зачем переименовывать в signUp? Потому что это, если смотреть со стороны кода, не форма а блок - article? hotelSearch и form-find-froom говорят почти об одном и том же. Только мое название уточняет что это компонент форма
По текстовым полям - есть какие-то замечания? Блок text-field-subscription говорит "Я текстовое поле подписки". Но на самом деле его миксин выдает форму. Будет правильным его назвать form-subscription?
По хедеру - у нас есть блок main-header, но в разных вариациях. Можно сделать один миксин и в тип передавать theme: authorized или еще как-то? Также с футером

**Comment by GoodDayTodayOkey** [comment]
https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

**Comment by madnessJs** [comment]
кебаб кейс
![image](https://user-images.githubusercontent.com/46949445/65687315-d7ebec80-e071-11e9-954a-a189c410b3af.png)

**Comment by GoodDayTodayOkey** [comment]
А у тебя по другому? 
![Снимок экрана от 2019-09-26 19-45-40](https://user-images.githubusercontent.com/31854808/65689171-a76a7980-e096-11e9-83d2-31a16d030683.png)
![Снимок экрана от 2019-09-26 19-45-51](https://user-images.githubusercontent.com/31854808/65689172-a76a7980-e096-11e9-958f-c40e70d318fd.png)
![Снимок экрана от 2019-09-26 19-47-40](https://user-images.githubusercontent.com/31854808/65689174-a8031000-e096-11e9-9639-2bf158e47ba5.png)

**Comment by GoodDayTodayOkey** [comment]
По второму вопросу да, только тему которую ты передаешь  будет использоваться для модификатора, а следовательно она должна соответствовать БЭМу.

**Comment by madnessJs** [comment]
> А у тебя по другому?
> ![Снимок экрана от 2019-09-26 19-45-40](https://user-images.githubusercontent.com/31854808/65689171-a76a7980-e096-11e9-83d2-31a16d030683.png)
> ![Снимок экрана от 2019-09-26 19-45-51](https://user-images.githubusercontent.com/31854808/65689172-a76a7980-e096-11e9-958f-c40e70d318fd.png)
> ![Снимок экрана от 2019-09-26 19-47-40](https://user-images.githubusercontent.com/31854808/65689174-a8031000-e096-11e9-9639-2bf158e47ba5.png)

Я к тому, что ты говорил вы не используете кебаб кейс. А на сайте компонент называется ghost-button. Значит используете

**Comment by madnessJs** [comment]
> По второму вопросу да, только тему которую ты передаешь будет использоваться для модификатора, а следовательно она должна соответствовать БЭМу.

Вроде бы понял. Занимаюсь сейчас как раз этим issue. Не думал, что будет так сложно)

**Comment by GoodDayTodayOkey** [comment]
По третьему вопросу, за время ревью мы натаскиваем стажеров для того чтобы в дальнейшем нам было комфортно с ними работать. Ты сейчас создаешь никому не нужные вложенности по папкам, и не верно  исходишь из позиции именования, следовательно от тебя это следует ожидать и на реальных проектах, а это уже будет дорогостоящими вещами, когда будет напилен код и его придется переделывать, из за неверных уровней вложенности, или мест расположения переиспользуемых уровней абстракции.

**Comment by GoodDayTodayOkey** [comment]
У нас действительно высокие требования на вход, и стандарты проектирования кода, но и отличная система развития  программистов, все зависит от желания и способностей кандидатов.
По поводу кеба кэйс где то в стандартах есть описанный этот пункт. И этот пример не из реального проекта))

**Comment by GoodDayTodayOkey** [comment]
По четвертому пункту, да подойдет, но не забывай про кэмел кэйс)

**Comment by madnessJs** [comment]
> По третьему вопросу, за время ревью мы натаскиваем стажеров для того чтобы в дальнейшем нам было комфортно с ними работать. Ты сейчас создаешь никому не нужные вложенности по папкам, и не верно исходишь из позиции именования, следовательно от тебя это следует ожидать и на реальных проектах, а это уже будет дорогостоящими вещами, когда будет напилен код и его придется переделывать, из за неверных уровней вложенности, или мест расположения переиспользуемых уровней абстракции.

Ну я вроде бы не говорил, что я прав. Я наоборот готов к любым замечания.
Ошибки есть естественно, тк я только учусь.

**Comment by madnessJs** [comment]
> По четвертому пункту, да подойдет, но не забывай про кэмел кэйс)

нашел
![image](https://user-images.githubusercontent.com/46949445/65690421-ae35c400-e077-11e9-8f6f-90371f56b894.png)

**Comment by GoodDayTodayOkey** [comment]
По пятому пункту почему блоки называются как main-header и main-footer? Есть и не основные? Если вопрос связан со стилизацией, то конечно можно регулировать все с помощью тем модификаторов. По четвертому пункту сорри, да ты прав. Для именования класса мы используем кебаб вейс, а для именования файла кэмйл кейс, это пример из реального проекта. 
![Снимок экрана от 2019-09-26 20-22-33](https://user-images.githubusercontent.com/31854808/65691682-7771a500-e09b-11e9-9dbf-ec76353c12aa.png)

**Comment by GoodDayTodayOkey** [comment]
По последнему пункту ты смотрел https://pugjs.org/language/mixins.html#mixin-blocks ? можно добавлять внутрь миксина верстку, это не поможет?

**Comment by madnessJs** [comment]
> По последнему пункту ты смотрел https://pugjs.org/language/mixins.html#mixin-blocks ? можно добавлять внутрь миксина верстку, это не поможет?

пропустил ссылку на статью...
Ого, очень удобно, спасибо. Завтра за этот issue примусь
Спасибо за разъяснения!

**Comment by GoodDayTodayOkey** [comment]
В целом это ишью уже близко к закрытию осталось подправить мелочи:
![Снимок экрана от 2019-09-29 07-36-47](https://user-images.githubusercontent.com/31854808/65824213-54a7e200-e28f-11e9-8d34-97d88ca93dea.png)
тут у тебя все имеют один и тоже класс элемента, поэтому объявляй его через точечную нотацию, а динамически задавай только меняющуюся часть, к примеру вот так.
![Снимок экрана от 2019-09-29 08-10-56](https://user-images.githubusercontent.com/31854808/65824308-e7954c00-e290-11e9-9a41-7a14dd47de58.png)
тут сразу же еще один момент для линк создай отдельную папку.
Этот момент у тебя повторяется о многих блоках, там тоже подправь.
Далее переименуй блок log-in => sign-in, а тот что сейчас sign-in в sign-up.
Не понятно для чего дропдауну эти параметры?
![Снимок экрана от 2019-09-29 07-44-28](https://user-images.githubusercontent.com/31854808/65824365-f16b7f00-e291-11e9-9c65-190f72e58ea7.png)
Вот здесь лучше оформить это отдельным блоков  и элемент inf0__subtitle сделать элементом этого блока
![Снимок экрана от 2019-09-29 07-48-40](https://user-images.githubusercontent.com/31854808/65824373-03e5b880-e292-11e9-94bd-c6b7530534f8.png)
![Снимок экрана от 2019-09-29 07-48-58](https://user-images.githubusercontent.com/31854808/65824377-0ba55d00-e292-11e9-876d-dd5aec0b1182.png)
![Снимок экрана от 2019-09-29 07-49-31](https://user-images.githubusercontent.com/31854808/65824378-0ba55d00-e292-11e9-91a5-1a3ab547a348.png)

**Comment by madnessJs** [comment]
> Не понятно для чего дропдауну эти параметры?
> ![Снимок экрана от 2019-09-29 07-44-28](https://user-images.githubusercontent.com/31854808/65824365-f16b7f00-e291-11e9-9c65-190f72e58ea7.png)

эмм... для отправки в обработчик формы.
id для связи label <--> input
name для именования поля
placeholder )
и readonly, для настройки поля как "только для чтения". Чтобы выбор в этом поле был только через js, тк это же дропдаун. И с этим атрибутом не показывается клавиатура на мобильных устройствах

**Comment by madnessJs** [comment]
Как ты смотришь на то, чтобы объединить text-input с dropdown? Будет одно текстовое поле с модификатором меняющим внешний вид
