### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [madnessJs/toxin#30]
В pug-файлах используются везде двойные кавычки, исправь пожалуйста в файлах **components-page.pug** и **room-page.pug**
![1](https://user-images.githubusercontent.com/19621113/70227373-8b084e80-1763-11ea-9f5b-bb894db9adfe.png)

**Comment by Nelliza** [comment]
![2](https://user-images.githubusercontent.com/19621113/70234711-4fc14c00-1772-11ea-899f-b40f45e69057.png)
Можешь подсказать, какую логику подразумевает этот кусок кода?

**Comment by madnessJs** [comment]
> ![2](https://user-images.githubusercontent.com/19621113/70234711-4fc14c00-1772-11ea-899f-b40f45e69057.png)
> Можешь подсказать, какую логику подразумевает этот кусок кода?

Для поля подписки на расслылку(в футере)
![image](https://user-images.githubusercontent.com/46949445/70235082-2c4ad100-1773-11ea-8601-cbda2f32df1a.png)

**Comment by madnessJs** [comment]
Хотя это было лишним. Убрал этот кусок кода. Сделал добавление кнопки по условию внутри миксина

**Comment by Nelliza** [comment]
Амперсанд желательно использовать только перед:
- разделителем БЭМ-элемента,
- разделителем БЭМ-модификатора,
- псевдоэлементом или псевдоселектором,

и не использовать в местах разделения словосочетаний имен БЭМ-сущностей (подробнее об этом [здесь](https://nicothin.pro/idiomatic-pre-CSS/#amp))

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/70385411-09e8cb80-199e-11ea-888a-7c74e332d6aa.png)

Амперсанд желательно использовать только перед:
- разделителем БЭМ-элемента,
- разделителем БЭМ-модификатора,
- псевдоэлементом или псевдоселектором,

и не использовать в местах разделения словосочетаний имен БЭМ-сущностей (подробнее об этом [здесь](https://nicothin.pro/idiomatic-pre-CSS/#amp))

**Comment by Nelliza** [comment]
Вот эту строчку тогда в **components-page.pug** нужно убрать теперь )
![1](https://user-images.githubusercontent.com/19621113/70386022-ec6b3000-19a4-11ea-9940-6e7ae131e548.png)

**Comment by Nelliza** [comment]
**rating.pug**
![1](https://user-images.githubusercontent.com/19621113/70863643-3f238980-1f5b-11ea-8841-ece965507cc2.png)

По [стандартам Airbnb](https://github.com/airbnb/javascript/#variables--unary-increment-decrement), использования инкрементов / декрементов следует избегать

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/71014689-65842900-2103-11ea-9c9e-ec929e39fc36.png)

Исправь пожалуйста здесь опечатку еще )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/71017632-e2190680-2107-11ea-9014-b24e7c986669.png)

Для чего здесь этот кусок кода, если функционал авторизации не реализован в проекте? )

**Comment by madnessJs** [comment]
> ![1](https://user-images.githubusercontent.com/19621113/71017632-e2190680-2107-11ea-9014-b24e7c986669.png)
> 
> Для чего здесь этот кусок кода, если функционал авторизации не реализован в проекте? )

В ui-kit представлен
![image](https://user-images.githubusercontent.com/46949445/71075300-df182780-2194-11ea-86fd-f4d9567f5aae.png)

**Comment by Nelliza** [comment]
> > ![1](https://user-images.githubusercontent.com/19621113/71017632-e2190680-2107-11ea-9014-b24e7c986669.png)
> > Для чего здесь этот кусок кода, если функционал авторизации не реализован в проекте? )
> 
> В ui-kit представлен
> ![image](https://user-images.githubusercontent.com/46949445/71075300-df182780-2194-11ea-86fd-f4d9567f5aae.png)

Не, насколько я поняла, это интерактивное отображение действий пользователей в интерфейсе самой фигмы )
