### ISSUE TITLE
Именование файлов

### ISSUE THREAD

**Issue by Nelliza** [madnessJs/toxin#32]
Именование файлов должно быть единообразным во всем проекте и выполненным в стиле `lower-case-hyphenated`

**Comment by madnessJs** [comment]
У меня так было по началу. Но 1 проверяющий сказал сделать в виде кебабкейса (вотТак). Так как в команде используется такой стиль

**Comment by madnessJs** [comment]
![image](https://user-images.githubusercontent.com/46949445/70236465-0246de00-1776-11ea-955c-aaa2032d75ac.png)

**Comment by Nelliza** [comment]
Вот здесь для изображений используй плиз тоже `lower-case-hyphenated`:
![1](https://user-images.githubusercontent.com/19621113/70386106-46202a00-19a6-11ea-8f44-e467d67abd1a.png)

А вот здесь нужны более подходящие имена, чем просто цифры:
![2](https://user-images.githubusercontent.com/19621113/70386116-67811600-19a6-11ea-9b72-cb79c7b4caf6.png)
![3](https://user-images.githubusercontent.com/19621113/70386119-81baf400-19a6-11ea-93b1-cc692c5dc965.png)

**Comment by Nelliza** [comment]
И вот здесь еще остались в `camelCase`-стиле:
![4](https://user-images.githubusercontent.com/19621113/70386149-04dc4a00-19a7-11ea-9c18-ea20d259ed9e.png)

**Comment by Nelliza** [comment]
И здесь еще остались в `camelCase`-стиле:
![4](https://user-images.githubusercontent.com/19621113/70386161-31906180-19a7-11ea-8781-966bbbd664b2.png)
