### ISSUE TITLE
Размеры элементов

### ISSUE THREAD

**Issue by Nelliza** [madnessJs/toxin#36]
**header.scss**

![1](https://user-images.githubusercontent.com/19621113/70385154-78c52500-199c-11ea-9920-f45010817823.png)

Здесь `.header__logo` - это ссылка, т.е. строчный элемент. Размеры строчных элементов определяются их содержимым, и задание для них свойств `width` и `height` бесполезно, т.к. они просто игнорируются

**Comment by Nelliza** [comment]
Для тега `img` (`.header__logo-image`) ты также задал жестко и `width`, и `height`, что нежелательно по нашим стандартам:
> 10. **Тегу `<img>` стараться не выставлять одновременно `width` и `height` - тогда велика вероятность, что будут нарушены пропорции картинки. Если у картинки все-таки должны быть по макету четкие размеры, то сделать все через `<div>`, у которого картинка лежит на фоне и применить `background-size: cover`**;

То же самое для `.footer__logo-image`, `.room__img` + посмотри пожалуйста еще по проекту аналогичные случаи

**Comment by madnessJs** [comment]
> **header.scss**
> 
> ![1](https://user-images.githubusercontent.com/19621113/70385154-78c52500-199c-11ea-9920-f45010817823.png)
> 
> Здесь `.header__logo` - это ссылка, т.е. строчный элемент. Размеры строчных элементов определяются их содержимым, и задание для них свойств `width` и `height` бесполезно, т.к. они просто игнорируются

По дефолту, конечно. Но в моем случае ссылка flex-element, тк находится внутри флекс-контейнера)

**Comment by Nelliza** [comment]
> По дефолту - конечно. Но в моем случае ссылка flex-element, тк находится внутри flex-container)

Справедливое дополнение ) Не заметила, что родитель - flex-container
