### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#4]
Сейчас весь проект выполнен не по БЭМ. Используй возможности препроцессоров, не дублируй именования блоков(которые сейчас у тебя являются элементами почему то). Не нужно динамически создавать классы, в стилях ты все равно привязываешь к одному блоку. 
![Снимок экрана от 2019-08-29 21-26-20](https://user-images.githubusercontent.com/31854808/63948931-c5e35200-caa3-11e9-9fb4-0215c4443b33.png)

**Comment by madnessJs** [comment]
![image](https://user-images.githubusercontent.com/46949445/63997651-c6adcf80-cb07-11e9-997a-6bafde1f93a3.png)
Т.е. как то так? И если мне нужно будет обратиться к заголовку, например, я обращаюсь каскадом? class c-advantage__lead ?

**Comment by GoodDayTodayOkey** [comment]
Нет, не нужно передавать в миксин класс, и потом его использоваться совместно блоком в одной дивке. (класс не стоит задавать динамически) К тому же при именовании мы не используем сокращения.

**Comment by madnessJs** [comment]
"мы не используем миксы" - тут не очень понял, что значит "миксы"?
![image](https://user-images.githubusercontent.com/46949445/64507692-13519180-d2e4-11e9-9002-953764be3912.png)
Вот таким образом должен миксин компонента выглядеть?

**Comment by GoodDayTodayOkey** [comment]
да, только используй точечную нотацию.

**Comment by GoodDayTodayOkey** [comment]
Используй возможности препроцессоров, не дублируй именование блоков
![Снимок экрана от 2019-09-13 17-03-11](https://user-images.githubusercontent.com/31854808/64854675-64e17f80-d648-11e9-8df9-434ff7921dfe.png)

**Comment by GoodDayTodayOkey** [comment]
Удали лишние строки в стилях сразу

**Comment by madnessJs** [comment]
> Удали лишние строки в стилях сразу

лишние в смысле "лишние" или "последние"? Можно пример?

**Comment by GoodDayTodayOkey** [comment]
На картинки выше, display: block и font-weight: bold разделены строкой.

**Comment by GoodDayTodayOkey** [comment]
Для чего необходим этот класс? 
![Снимок экрана от 2019-09-13 17-08-55](https://user-images.githubusercontent.com/31854808/64855051-39ab6000-d649-11e9-949e-2b4136e9e91e.png)

**Comment by madnessJs** [comment]
> На картинки выше, display: block и font-weight: bold разделены строкой.

Аа, ну я специально разделяю. Чтобы было легко ориентироваться в стилях. Сначала позиционирование элемента, потом блочная модель и тд. Ну хорошо, удалю

**Comment by GoodDayTodayOkey** [comment]
Не все картинки перенесены в папку images

**Comment by madnessJs** [comment]
> Для чего необходим этот класс?
> ![Снимок экрана от 2019-09-13 17-08-55](https://user-images.githubusercontent.com/31854808/64855051-39ab6000-d649-11e9-949e-2b4136e9e91e.png)

для расширения блока button добавлением стрелки на кнопку/ссылку

**Comment by GoodDayTodayOkey** [comment]
а где он используется? Я по коду не нашел это класс

**Comment by madnessJs** [comment]
> а где он используется? Я по коду не нашел это класс

ммм, нигде)

**Comment by GoodDayTodayOkey** [comment]
У тебя там все кнопки везде представлены то ссылками то кнопками, вот статья которая поможет оформить их кнопками, https://www.w3docs.com/snippets/html/how-to-create-an-html-button-that-acts-like-a-link.html К тому же все можно создать один блок, батон, а разнообразные виды оформлять с помощью модификаторов этого блока
![Снимок экрана от 2019-09-13 17-47-38](https://user-images.githubusercontent.com/31854808/64857438-b42aae80-d64e-11e9-970c-16711283f2c0.png)

**Comment by GoodDayTodayOkey** [comment]
классы которые используются в js  должны иметь префикс js-
![Снимок экрана от 2019-09-13 17-51-03](https://user-images.githubusercontent.com/31854808/64857646-53e83c80-d64f-11e9-9c7c-47424a73d36c.png)
