### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#5]
Используй преимущества препроцессоров не дублируй именование блоков
![Снимок экрана от 2019-09-16 12-43-33](https://user-images.githubusercontent.com/31854808/64936383-dce5ba80-d87f-11e9-9a8f-93687be13780.png)

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-20 21-47-40](https://user-images.githubusercontent.com/31854808/65336308-579c3600-dbf0-11e9-8d39-87ce34649a78.png)

**Comment by madnessJs** [comment]
тут тоже. Не лез в стили плагинов

**Comment by GoodDayTodayOkey** [comment]
тут тоже нужно подправить
![Снимок экрана от 2019-09-24 18-26-12](https://user-images.githubusercontent.com/31854808/65508069-959f9f80-def9-11e9-9c07-a4c287c44711.png)
![Снимок экрана от 2019-09-24 18-26-20](https://user-images.githubusercontent.com/31854808/65508070-96383600-def9-11e9-8e49-668b11ced43e.png)
![Снимок экрана от 2019-09-24 18-31-22](https://user-images.githubusercontent.com/31854808/65508071-96383600-def9-11e9-8126-9a4f63370f1e.png)
![Снимок экрана от 2019-09-24 18-31-38](https://user-images.githubusercontent.com/31854808/65508072-96383600-def9-11e9-94ca-8b2b3021194a.png)
пройдись плиз по всему проекту на подобные замечания

**Comment by madnessJs** [comment]
А что не так?

**Comment by GoodDayTodayOkey** [comment]
Тут повторяются именования родителя)

**Comment by GoodDayTodayOkey** [comment]
А где где то в блок запихнут вообще другой блок)

**Comment by GoodDayTodayOkey** [comment]
В scss можно объявлять переменную с именем блока и потом ее использовать 
![Снимок экрана от 2019-09-25 15-53-40](https://user-images.githubusercontent.com/31854808/65585483-ba088400-dfac-11e9-851b-b383f7c926a3.png)
![Снимок экрана от 2019-09-25 15-53-34](https://user-images.githubusercontent.com/31854808/65585492-be34a180-dfac-11e9-99b0-34b7919eaed4.png)
