### ISSUE TITLE
Финальные замечания

### ISSUE THREAD

**Issue by Sergio-Ka** [madnessJs/toxin#58]
1. Шрифты именованы с большой буквы (противоречит пункту об именовании подключаемых файлов, которые должны именоваться в стиле lower-case-hyphenated).
2. Точки с запятой в выражениях js в pug файлах не стоят (экранируемые знаком тире выражения в pug файлах - это фактически js, а на него распространяются все те правила AirBnB, что указаны в стандартах).
3. Тег b встречается в файлах pug (определяет жирное начертание, а хорошей практикой считается разделение структуры и представления, а применение этого тега равносильно использованию инлайновых стилей).
4. Ненадлежащим образом оформленные компоненты в pages (отсутствует БЭМ в плане оформления структуры (каждый блок миксин в своей папке со своими реализациями) и компонентность) Там сейчас можно увидеть такой кусок кода состоящий из бэм блоков, но без миксинов. И стили для двух разных блоков лежат в одном стилевом файле:
```
main.components-page
    h1.components-page__title.components-page__title_hidden Компоненты проекта
    article.ui-kit
      h2.ui-kit__title Цвета и шрифты
      .ui-kit__group
        ul.ui-kit__list
```
5. Такого рода пути будeт затруднять переиспользование блоков (компонент) background-image: url('../../components/advantage/images/comfort.svg'); (здесь для примера компонент advantage, вообще такое во многих компонентах я вижу). Ты ведь не можешь гарантировать повторяемость структуры папок например в каком-то другом проекте, а значит все эти пути придется править, хотя папка images лежит рядом. Лучше что-то типа background-image: url('./images/comfort.svg');
6. Многие блоки включают обнуление марджинов и паддингов - это во-первых внешнее поведение (что по БЭМ запрещено), во-вторых лишний код - можно задать для всего проекта обнуление марджинов и паддингов через универсальный селектор *.
7. Константы (например в календаре). Лучше создавать отдельные модули для констант, выносить их туда, и потом импортировать их. Такие модули можно делать и на уровне компопненты (если специфичная для нее информация) и на уровне проекта. В стандарте это звучит как: "Не использовать литералы из бизнес-логики напрямую - надо создавать объект с константами".

**Comment by madnessJs** [comment]
По 3 пункту вопрос. А использование тегов strong и em тоже не приветствуется? Они тоже выделяют часть текста, но также и придают ей смысл. Как быть в этом случае?

**Comment by madnessJs** [comment]
По 4 пункту. Один блок = один миксин, а если это страница? Как у меня в проекте. Страница index-page содержит в себе один блок, стилевой файл и файл js. Это годится?

**Comment by Sergio-Ka** [comment]
3. Вообще все теги которые влияют на отображение я думаю стоит считать плохими как раз по причине того, что должно быть разделение структуры и представления. Тэг strong имеет семантическое значение (акцент), em туда же. Если они нужны с точки зрения семантики именно как выделение какого-то момента в тексте - то да, можно пользовать. При этом я сомневаюсь что они пойдут в качестве заголовка, для этих целей семантичнее будут другие теги. Тег же b - это визуальное оформление, а за оформление должен отвечать CSS.
4. Здесь я говорю о том, что если у тебя в той же index-page есть бэм-блок main.main-page то он и должен быть оформлен как компонент - то есть в виде миксина, в своей папке со своими реализациями и лежать в подпапке components где лежат остальные блоки. При этом в файле index.pug он должен вызываться миксином (типа +main-page). При этом этот миксин не обязательно должен принимать какие-то параметры (хотя теоретически может от самого корня и распределять их внутри себя по другим компонентам-миксинам). Смысл всего этого - компонентность, исключений нет, внутренние ли это блоки или корневые. А тут получается что ты поставил страницы в какое-то привелегированное положение, хотя разницы нет и в БЭМ нет для этого структурных единиц, там только блоки, элементы и модификаторы, а значит все что есть это блоки,даже те же страницы.
5. С parcel не знаком если честно. Ладно, тогда пусть как есть останется, главное понимать почему это плохо.
6. Это по хорошему влияние на окружающую среду, так как возможно какой-то блок без обнуления ведет себя как-то по другому как от него ожидают и не так как при обнулении. Это во-первых. Во-вторых, указание где-нибудь в корне через универсальный селектор - не такая и плохая практика, так как у него вообще нет приоритета и он перебивается любым правилом. Кроме того это достаточно часто встречается и достаточно неплохо воспринимается так как лежит в одном месте. Ну и в-третьих, а так ли там вообще нужны эти обнуления? У элементов html есть свое поведение как правило и там не так много таких, которые ведут себя не адекватно (как правило списки какие-нибудь, инпуты) и едва ли это какие-то блочные элементы. К чему это лишний код? Обнуление дефолтных отступов принято делать в одном общем корневом файле через универсальный селектор или конкретно по тегам, о чем я выше написал, есть еще какие-то причины?

**Comment by madnessJs** [comment]
По 6 пункту. Исходил из собственного понимания и глав из [статья 1](https://medium.com/@innabelaya/%D0%B1%D1%8D%D0%BC-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%8E%D1%89%D0%B8%D1%85-%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%BD%D0%B5%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B8-1a21d67cf840#7026), [статья 2 п. 4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)
Я сбрасывал только стили, которые включает браузер, например списки, параграфы. Может подробнее на примере какого-нибудь блока объяснишь почему не стоит делать так как я?

**Comment by Sergio-Ka** [comment]
6.  В том и дело что ты их только сбрасываешь, но потом не задаешь новые потому что нельзя блокам по БЭМ задавать марджины. Кроме того разные браузеры ведут себя по разному, какие-то дают отступы, какие-то нет. А стало быть проще, нагляднее и быстрее сбрасывать из корня через универсальный селектор.
7. вообще то что повторяется и имеет отношение к настройкам или инициализации. Или какие-то магические числа (термин из Питера Гудлифа Ремесло программиста). В данном случае да, потому как одно дело воспринимать это тут же в коде как
```
this.$fieldInit.datepicker({
      prevHtml:
        '<svg style="width: 24px; height: 24px;" width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Предыдущий месяц"><path style="transform:translate(-15%,-15%) rotate(180deg); transform-origin: center center; fill: #BC9CFF; stroke: none" d="M8.363.984L16.378 9l-8.015 8.016-1.407-1.407 5.578-5.625H.347V8.016h12.187L6.956 2.39 8.363.984z" fill="#BC9CFF"/></svg>',
      nextHtml:
        '<svg style="width: 24px; height: 24px;" width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Следующий месяц"><path style="transform:translate(15%,15%); fill: #BC9CFF; stroke: none" d="M8.363.984L16.378 9l-8.015 8.016-1.407-1.407 5.578-5.625H.347V8.016h12.187L6.956 2.39 8.363.984z" fill="#BC9CFF"/></svg>',
      navTitles: {
        days: 'MM yyyy',
      },
      minDate: new Date(),
      offset: 9,
      range: true,
      multipleDatesSeparator: '-',
      inline: true,
      onSelect: this.handleCalendarSelectedData.bind(this),
    });
```
и другое дело как-нибудь так:
this.$fieldInit.datepicker({...constants.DEFAULT_CALENDAR_PARAMETRS,
      onSelect: this.handleCalendarSelectedData.bind(this),
    });

А вообще тут стоит посмотреть по всему проекту такие моменты.
