### ISSUE TITLE
Импортируй стили автоматически

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#7]
Можно автоматический рекваирить стили внутри index.js, чтобы случайно не забыть что то прикрепить. Так же с  js-ками.

**Comment by madnessJs** [comment]
> Можно автоматический рекваирить стили внутри index.js, чтобы случайно не забыть что то прикрепить. Так же с js-ками.

Я к каждой странице цепляю 1 css и 1 js файл, поэтому я не забуду)
Если нужно, то исправлю.
И насчет "Так же с js-ками." не понял. js внутри js рекваирить?)

**Comment by GoodDayTodayOkey** [comment]
я о подобном писал
![Снимок экрана от 2019-09-20 21-58-42](https://user-images.githubusercontent.com/31854808/65337256-02612400-dbf2-11e9-8df8-3ced77bdf0d1.png)
![Снимок экрана от 2019-09-20 21-58-50](https://user-images.githubusercontent.com/31854808/65337257-02612400-dbf2-11e9-96a3-b288ab28cac3.png)

**Comment by madnessJs** [comment]
Все равно не понял

**Comment by GoodDayTodayOkey** [comment]
https://webpack.js.org/guides/dependency-management/

function requireAll(r) {
  return r.keys().map(r);
}
requireAll(require.context('src', true, /\.scss$/));

**Comment by madnessJs** [comment]
> https://webpack.js.org/guides/dependency-management/
> 
> function requireAll(r) {
> return r.keys().map(r);
> }
> requireAll(require.context('src', true, /.scss$/));

У меня parcel. Но я думаю это тоже самое https://parceljs.org/assets.html#javascript
