### ISSUE TITLE
Не дублируй повторяющийся код

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [madnessJs/toxin#9]
Используй преимущества препроцессоров не дублируй повторяющийся код, (проходись с замечаниями сразу по всему проекту, чтобы не пришлось их после повторять)

**Comment by madnessJs** [comment]
дублирование issue #5

**Comment by madnessJs** [comment]
> Используй преимущества препроцессоров не дублируй повторяющийся код, (проходись с замечаниями сразу по всему проекту, чтобы не пришлось их после повторять)

Вроде все норм по этому пункту...
Я сразу по всему проекту и пробегаю. Просто я не имел раньше дел с такими большими проектами, поэтому могу что-то упустить. Но я стараюсь и если, что то пиши я буду исправлять

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-20 21-53-30](https://user-images.githubusercontent.com/31854808/65336737-1bb5a080-dbf1-11e9-9379-a97558d131d7.png)
просмотри плиз еще раз проект на это ишью

**Comment by madnessJs** [comment]
> ![Снимок экрана от 2019-09-20 21-53-30](https://user-images.githubusercontent.com/31854808/65336737-1bb5a080-dbf1-11e9-9379-a97558d131d7.png)
> просмотри плиз еще раз проект на это ишью

А что тут нужно? В цикле запустить вывод 4-х лишек?

**Comment by GoodDayTodayOkey** [comment]
Да, хорошо, что их 4 а не 20 было бы не так удобно) К тому здесь можно было назвать элемент donut__evaluation и менять только текст)

**Comment by madnessJs** [comment]
> Да, хорошо, что их 4 а не 20 было бы не так удобно) К тому здесь можно было назвать элемент donut__evaluation и менять только текст) Пройдись плиз по проекту на подобные места, пока ишью закрывать не буд.

Примерно так должно выглядеть?
![image](https://user-images.githubusercontent.com/46949445/65522421-684ff300-def3-11e9-82d5-c222c0f04d44.png)

**Comment by GoodDayTodayOkey** [comment]
Да, только массив можно вынести  константу.

**Comment by madnessJs** [comment]
Съехал хедер немного после коммита) Это я не уследил. С новым коммитом залью исправление

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-26 20-57-20](https://user-images.githubusercontent.com/31854808/65694612-58c1dd00-e0a0-11e9-8415-04a71a855e84.png)
Вот здесь лучше вынести в миксин, чтобы избавить от if-ов

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-29 08-38-47](https://user-images.githubusercontent.com/31854808/65824508-99824780-e294-11e9-8a97-eb08596d85b1.png)

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-09-29 08-41-55](https://user-images.githubusercontent.com/31854808/65824545-101f4500-e295-11e9-9ad9-b3fa01e8e64e.png)
![Снимок экрана от 2019-09-29 08-42-02](https://user-images.githubusercontent.com/31854808/65824546-101f4500-e295-11e9-9cd6-c8becf705992.png)

**Comment by GoodDayTodayOkey** [comment]
В целом норм, осталось подправить 4 момента
вот здесь поменяй у себя в коде signup => signUp в пути а то не у всех отображается)
![Снимок экрана от 2019-10-02 15-41-42](https://user-images.githubusercontent.com/31854808/66031967-a752f980-e52e-11e9-90c7-03f7ab0a0b4b.png)
тут занеси name checked внутрь объекта и также пробегись циклом
![Снимок экрана от 2019-10-02 15-15-27](https://user-images.githubusercontent.com/31854808/66031987-b5087f00-e52e-11e9-9bcc-a617c2769fb6.png)
![Снимок экрана от 2019-10-02 15-15-20](https://user-images.githubusercontent.com/31854808/66031998-b89c0600-e52e-11e9-87e5-c0faa3c43568.png)
![Снимок экрана от 2019-10-02 15-13-06](https://user-images.githubusercontent.com/31854808/66032006-bf2a7d80-e52e-11e9-998a-ab99f0921bd5.png)

например checkboxInput можно так оформить 
![Снимок экрана от 2019-10-02 16-22-49](https://user-images.githubusercontent.com/31854808/66033220-03b71880-e531-11e9-9baf-f46f946d9a6c.png)

![Снимок экрана от 2019-10-02 16-23-29](https://user-images.githubusercontent.com/31854808/66033207-fdc13780-e530-11e9-8faa-44efc750040e.png)
не обязательно переносить все свойства лишь те что мешают оформить в цикле коде

**Comment by madnessJs** [comment]
хмм, атрибут disabled отлючает поле при любом своем значении, также как и атрибут checked (даже false). Пока нет понятия как его передавать в миксин...

**Comment by GoodDayTodayOkey** [comment]
Странно у меня все меняется
![Peek 2019-10-02 18-54](https://user-images.githubusercontent.com/31854808/66042285-3c152180-e546-11e9-8b9c-9eee99ea91b9.gif)
![Снимок экрана от 2019-10-02 18-55-29](https://user-images.githubusercontent.com/31854808/66042341-61099480-e546-11e9-9a57-8b1ef8b0993f.png)

**Comment by madnessJs** [comment]
Попробовал сейчас - все работает. И с атрибутом checked и с disabled...
Либо я вчера переработал, либо я не знаю)
